# Generated by Django 3.2.25 on 2024-07-16 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dam_monitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoringsample',
            name='model_run',
        ),
        migrations.AddField(
            model_name='monitoringpoint',
            name='model_run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dam_monitor.modelrun'),
        ),
    ]
